# Generated by Django 3.0.2 on 2020-03-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewalletapp', '0004_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
