# Generated by Django 3.0.2 on 2020-03-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewalletapp', '0005_remove_profile_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jio',
            fields=[
                ('mobile_number', models.IntegerField(blank=True, max_length=10, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(max_length=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vodafone',
            fields=[
                ('mobile_number', models.IntegerField(blank=True, max_length=10, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(max_length=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
