# Generated by Django 3.0.2 on 2020-03-06 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ewalletapp', '0006_jio_vodafone'),
    ]

    operations = [
        migrations.AddField(
            model_name='jio',
            name='recharge_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vodafone',
            name='recharge_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
