# Generated by Django 3.0.4 on 2020-03-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewalletapp', '0009_auto_20200320_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/profile_pic.jpg', upload_to='images/'),
        ),
    ]
