# Generated by Django 3.0.4 on 2020-03-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewalletapp', '0010_auto_20200320_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
    ]
