# Generated by Django 3.0.4 on 2020-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewalletapp', '0013_auto_20200321_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='debit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
